---
  # General
  cuda: true
  wandb: true
  epochs: 120
  batch_size: 32
  val_step: 1
  ema: false
  workers: 4

  train_path: ./data/dev/images
  val_path: ./data/val/images

  sgd:
    lr: 0.001
    momentum: 0.9
    nesterov: true
    decay: 0.01
  
  scheduler: true

  # BCE loss weight
  pos_weight: 1.0
